import streamlit as st
import plotly.graph_objects as go
import time
from fpdf import FPDF
import io

# 1. Page Configuration
st.set_page_config(page_title="Diet Recommendation System", layout="wide", page_icon="🥗")

# --- SESSION STATE INITIALIZATION ---
if 'step' not in st.session_state: st.session_state.step = 1
if 'bmi_calculated' not in st.session_state: st.session_state.bmi_calculated = 0.0
if 'show_meals' not in st.session_state: st.session_state.show_meals = False
if 'user_data' not in st.session_state: st.session_state.user_data = {}
if 'animation_played' not in st.session_state: st.session_state.animation_played = False

# --- PDF GENERATION FUNCTION ---
def generate_pdf_report(data, bmi, status, goal, diet, meals):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_fill_color(10, 25, 47) 
    pdf.rect(0, 0, 210, 40, 'F')
    pdf.set_text_color(0, 242, 254) 
    pdf.set_font("Arial", 'B', 20)
    pdf.cell(190, 20, "DIET ANALYSIS REPORT", ln=True, align='C')
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Arial", 'B', 14)
    pdf.ln(25)
    pdf.cell(100, 10, "USER BIO-METRICS", ln=True)
    pdf.set_font("Arial", size=12)
    pdf.cell(100, 8, f"Age: {data.get('age', 'N/A')} years", ln=True)
    pdf.cell(100, 8, f"Height: {data.get('height', 'N/A')} cm", ln=True)
    pdf.cell(100, 8, f"Weight: {data.get('weight', 'N/A')} kg", ln=True)
    pdf.cell(100, 8, f"Calculated BMI: {bmi}", ln=True)
    pdf.cell(100, 8, f"Health Status: {status}", ln=True)
    pdf.ln(20)
    pdf.set_font("Arial", 'I', 8)
    pdf.cell(190, 10, "Generated by Juvva Uday Kumar - Diet Recommendation System", align='C')
    return pdf.output(dest='S').encode('latin-1')

# --- THE "AURORA LIQUID" CSS WITH IMAGE CLICK EFFECTS ---
st.markdown("""
    <style>
    @import url('https://fonts.googleapis.com/css2?family=Orbitron:wght@400;700&family=Inter:wght@300;400;600&display=swap');

    .stApp {
        background-color: #030405;
        background-image: 
            radial-gradient(at 0% 0%, hsla(210,100%,15%,1) 0, transparent 50%), 
            radial-gradient(at 50% 0%, hsla(225,80%,10%,1) 0, transparent 50%), 
            radial-gradient(at 100% 0%, hsla(200,100%,15%,1) 0, transparent 50%),
            radial-gradient(at 50% 100%, hsla(220,100%,10%,1) 0, transparent 50%);
        background-size: 200% 200%;
        animation: auroraFlow 15s ease infinite alternate;
        color: #e6edf3;
        font-family: 'Inter', sans-serif;
    }

    @keyframes auroraFlow {
        0% { background-position: 0% 0%; }
        100% { background-position: 100% 100%; }
    }

    .main-title {
        font-family: 'Orbitron', sans-serif;
        font-size: clamp(1.8rem, 5vw, 3rem);
        text-align: center;
        color: #ffffff;
        letter-spacing: 5px;
        font-weight: 700;
        padding-top: 60px;
        padding-bottom: 20px;
        text-shadow: 0 0 20px rgba(0, 242, 254, 0.4);
    }

    .glass-card {
        background: rgba(255, 255, 255, 0.02);
        border: 1px solid rgba(255, 255, 255, 0.08);
        border-radius: 25px;
        padding: 40px;
        backdrop-filter: blur(25px) saturate(160%);
        box-shadow: 0 15px 35px rgba(0, 0, 0, 0.4);
        margin-bottom: 30px;
    }

    /* --- IMAGE CLICK & HOVER EFFECTS --- */
    [data-testid="stImage"] {
        transition: all 0.4s cubic-bezier(0.175, 0.885, 0.32, 1.275);
        cursor: pointer;
    }

    [data-testid="stImage"] img {
        border-radius: 20px;
        height: 180px;
        object-fit: cover;
        border: 2px solid rgba(255, 255, 255, 0.1);
        transition: all 0.4s ease;
    }

    /* Hover Effect: Zoom and Glow */
    [data-testid="stImage"]:hover {
        transform: scale(1.08);
        filter: drop-shadow(0 0 15px rgba(0, 242, 254, 0.6));
        z-index: 10;
    }

    [data-testid="stImage"]:hover img {
        border-color: #00f2fe;
    }

    /* Click Effect: Shrink slightly when pressed */
    [data-testid="stImage"]:active {
        transform: scale(0.95);
        transition: 0.1s;
    }

    div.stButton > button {
        background: transparent;
        color: #00f2fe !important;
        font-family: 'Orbitron', sans-serif;
        font-weight: 700;
        border: 1px solid #00f2fe !important;
        padding: 12px 35px;
        border-radius: 10px;
        transition: 0.4s all ease;
        letter-spacing: 2px;
    }
    
    div.stButton > button:hover {
        background: #00f2fe !important;
        color: #030405 !important;
        box-shadow: 0 0 30px rgba(0, 242, 254, 0.6);
        transform: translateY(-3px);
    }

    .bmi-status {
        font-family: 'Orbitron', sans-serif;
        text-align: center;
        font-size: 26px;
        font-weight: bold;
        letter-spacing: 3px;
        margin-top: -10px;
    }

    .footer-text {
        text-align: center;
        font-family: 'Orbitron', sans-serif;
        font-size: 11px;
        color: rgba(255,255,255,0.2);
        margin-top: 100px;
        padding-bottom: 40px;
        letter-spacing: 8px;
    }
    </style>
    """, unsafe_allow_html=True)

# --- GLOBAL HEADER ---
st.markdown('<h1 class="main-title">DIET RECOMMENDATION SYSTEM</h1>', unsafe_allow_html=True)

# --- Assets ---
IMG_PAPAYA = "https://i.pinimg.com/736x/52/27/03/52270313640ccb03e825947f8d596c3f.jpg"
IMG_CUCUMBER = "https://cdn.deliciousmeetshealthy.com/wp-content/uploads/2017/07/Cucumber-Salad-Recipe-1.jpg"
IMG_STIR_VEG = "https://recipe30.com/wp-content/uploads/2021/08/Asian-stirfried-vegetables.jpg"
IMG_ALMOND = "https://tse2.mm.bing.net/th/id/OIP.PGisX0C9LbdpuFXDl6d4CQHaFj?pid=Api&P=0&h=180"
IMG_DATES = "https://www.verywellhealth.com/thmb/54XGtMFNCSvY4nV8rBsNg7EVq44=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/GettyImages-516816754-d3066527a1284216a16125d9fce2e1d0.jpg"
IMG_CHICKEN_BR = "https://tse1.mm.bing.net/th/id/OIP.ZZ9gGxDJlS1ikSdLGlI4IQHaHa?pid=Api&P=0&h=180"
IMG_FISH_CURRY = "https://amazingfoodanddrink.com/wp-content/uploads/2025/03/Best-Fish-Curry-Recipe-with-Coconut-or-Spicy-Variations.jpeg"

meal_db = {
    "Weight Loss": {
        "Veg": [
            ["Moong Dal Soup", "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400"], 
            ["Roasted Chana", "https://images.thequint.com/thequint/2024-01/401f9502-129b-4232-9d36-e566e38f1173/close_up_of_crunchy_roasted_chana_masala_in_black_ceramic_bowl_made_with_bengal_grams_or_jpg_s_1024x.jpg"], 
            ["Papaya Bowl", IMG_PAPAYA], ["Cucumber Salad", IMG_CUCUMBER]
        ],
        "Non-Veg": [
            ["Egg White Omelet", "https://savorthebest.com/wp-content/uploads/2025/01/egg-white-omelet-souffle-style-recipe_7155-1080x1080.jpg"], 
            ["Grilled Prawns", "https://tse1.mm.bing.net/th/id/OIP.YqnW02USmMa1ZU4RXOhqagHaJQ?pid=Api&P=0&h=180"], 
            ["Fish Curry", IMG_FISH_CURRY], ["Boiled Chicken", IMG_CHICKEN_BR]
        ]
    },
    "Weight Gain": {
        "Veg": [
            ["Sweet Potato", "https://tse3.mm.bing.net/th/id/OIP.-zuFWOil9YQXyIfhjyWWQQHaEg?pid=Api&P=0&h=180"], 
            ["Peanut Butter", "https://www.organicfacts.net/wp-content/uploads/peanutbutter1.jpg"], 
            ["Kaju Mix", "https://www.kajubadam.com/wp-content/uploads/2023/07/tukda_kaju_1kg-860x956.jpg"], ["Dates", IMG_DATES]
        ],
        "Non-Veg": [
            ["Whole Eggs", "https://tse3.mm.bing.net/th/id/OIP.vaRJBX_xRZ4FMyNqq0UK1wHaE8?pid=Api&P=0&h=180"], 
            ["Chicken & Rice", "https://tse3.mm.bing.net/th/id/OIP.0KtFD62H6cfHNdZ6mzGEdQHaJQ?pid=Api&P=0&h=180"], 
            ["Full Cream Milk", "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400"], ["Fish Curry", IMG_FISH_CURRY]
        ]
    },
    "Muscle Gain": {
        "Veg": [
            ["Paneer", "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=400"], 
            ["Soya Chunks", "https://tse3.mm.bing.net/th/id/OIP.nsg_mx9ZFgC0vqsbcYwp-wHaE8?pid=Api&P=0&h=180"], 
            ["Almonds", IMG_ALMOND], ["Stir Vegetables", IMG_STIR_VEG]
        ],
        "Non-Veg": [
            ["Chicken Breast", IMG_CHICKEN_BR], ["Grilled Prawns", "https://tse1.mm.bing.net/th/id/OIP.YqnW02USmMa1ZU4RXOhqagHaJQ?pid=Api&P=0&h=180"], 
            ["Fish Curry", IMG_FISH_CURRY], ["Boiled Egg Whites", "https://images.eatthismuch.com/img/1830459_MSF415_1b39160b-fcb3-4321-a023-3ced152aef2d.jpg"]
        ]
    }
}

# --- STEP 1: BIO-METRICS ---
if st.session_state.step == 1:
    st.markdown('<div class="glass-card">', unsafe_allow_html=True)
    c1, c2, c3 = st.columns(3)
    with c1: age = st.number_input("AGE", 1, 100, None, placeholder="Enter Your Age")
    with c2: h = st.number_input("HEIGHT (CM)", 1.0, 250.0, None, placeholder="Enter Your Height")
    with c3: w = st.number_input("WEIGHT (KG)", 1.0, 500.0, None, placeholder="Enter Your Weight")
    
    st.write("")
    _, mid, _ = st.columns([1, 0.4, 1])
    with mid:
        if st.button("RUN"):
            if h and w and age:
                st.session_state.bmi_calculated = round(w / ((h/100)**2), 1)
                st.session_state.user_data = {"age": age, "height": h, "weight": w}
                st.session_state.step = 2
                st.session_state.animation_played = False
                st.rerun()
            else: st.warning("⚠️ Inputs required.")
    st.markdown('</div>', unsafe_allow_html=True)

# --- STEP 2: RESULTS ---
else:
    st.markdown('<div class="glass-card">', unsafe_allow_html=True)
    bmi_final = st.session_state.bmi_calculated
    gauge_placeholder = st.empty()
    
    def render_gauge(val):
        fig = go.Figure(go.Indicator(
            mode = "gauge+number", value = val,
            domain = {'x': [0, 1], 'y': [0, 1]},
            title = {'text': "BMI METER", 'font': {'family': "Orbitron", 'color': "#ffffff", 'size': 18}},
            gauge = {
                'axis': {'range': [None, 45], 'tickwidth': 1, 'tickcolor': "white"},
                'bar': {'color': "#00f2fe", 'thickness': 0.3},
                'bgcolor': "rgba(0,0,0,0)",
                'steps': [
                    {'range': [0, 18.5], 'color': 'rgba(255, 75, 43, 0.2)'},
                    {'range': [18.5, 25], 'color': 'rgba(0, 242, 254, 0.2)'},
                    {'range': [25, 45], 'color': 'rgba(255, 183, 77, 0.2)'}]
            }
        ))
        fig.update_layout(paper_bgcolor='rgba(0,0,0,0)', font={'color': "#ffffff"}, height=300, margin=dict(t=50, b=0))
        return fig

    if not st.session_state.animation_played:
        for i in range(0, int(bmi_final) + 1):
            gauge_placeholder.plotly_chart(render_gauge(i), use_container_width=True)
            time.sleep(0.01)
        gauge_placeholder.plotly_chart(render_gauge(bmi_final), use_container_width=True)
        st.session_state.animation_played = True
    else:
        gauge_placeholder.plotly_chart(render_gauge(bmi_final), use_container_width=True)

    if bmi_final < 18.5: status, color = "UNDERWEIGHT", "#ff4b2b"
    elif 18.5 <= bmi_final < 25: status, color = "HEALTHY", "#00f2fe"
    else: status, color = "OVERWEIGHT", "#ffb74d"
    
    st.markdown(f'<p class="bmi-status" style="color:{color};">{status}</p>', unsafe_allow_html=True)
    st.markdown('</div>', unsafe_allow_html=True)

    st.markdown('<div class="glass-card">', unsafe_allow_html=True)
    col_a, col_b = st.columns(2)
    with col_a: goal_selected = st.selectbox("GOAL", list(meal_db.keys()))
    with col_b: diet_selected = st.radio("DIET", ["Veg", "Non-Veg"], horizontal=True)
    st.write("")
    _, mid2, _ = st.columns([1, 0.6, 1])
    with mid2:
        if st.button("GENERATE MEALS"): st.session_state.show_meals = True
    st.markdown('</div>', unsafe_allow_html=True)

    if st.session_state.show_meals:
        meals = meal_db[goal_selected][diet_selected][:4]
        m_cols = st.columns(len(meals))
        for i, col in enumerate(m_cols):
            with col:
                # Custom div structure used to wrap image to ensure hover effects work properly
                st.image(meals[i][1], use_container_width=True)
                st.markdown(f"<p style='text-align:center; font-weight:600; font-size:12px; color:#e6edf3; margin-top:10px;'>{meals[i][0]}</p>", unsafe_allow_html=True)

        pdf_bytes = generate_pdf_report(st.session_state.user_data, bmi_final, status, goal_selected, diet_selected, meals)
        st.write("---")
        _, d_mid, _ = st.columns([1, 0.6, 1])
        with d_mid:
            st.download_button("📥 DOWNLOAD PDF", pdf_bytes, f"Diet_Report_{goal_selected}.pdf", "application/pdf")

    if st.button("← RESET SYSTEM"):
        st.session_state.step = 1
        st.session_state.show_meals = False
        st.session_state.animation_played = False
        st.rerun()

st.markdown('<div class="footer-text">BY JUVVA UDAY KUMAR</div>', unsafe_allow_html=True)
